config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|id/ do
    resources :bus_types, except: :destroy
    resources :provinces, except: :destroy do
      resources :cities, except: [:show, :destroy]
    end
    resources :companies, except: :destroy
    root 'home#index'
  end

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Busify"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = nav_bar fixed: :top, responsive: true, brand: 'Busify' do
          = menu_group do
            = menu_item root_path do
              = fa_icon :home
              = _('Home')
            = menu_item provinces_path do
              = fa_icon :list
              = n_('Province', 'Provinces', 2)
            = menu_item bus_types_path do
              = fa_icon :list
              = n_('Bus type', 'Bus types', 2)
            = menu_item companies_path do
              = fa_icon :bus
              = n_('Company', 'Companies', 2)
          = menu_group pull: :right do
            = drop_down image_tag("#{FastGettext.locale == 'en' ? :en : :id}.png") do
              = menu_item "/#{FastGettext.locale == 'en' ? :id : :en}" do
                = image_tag("#{FastGettext.locale == 'en' ? :id : :en}.png")
                = _(FastGettext.locale == 'en' ? 'Indonesian' : 'English')

    .container
      = render_breadcrumbs("", class: '', item_class: '', divider_class: '', active_class: 'active', separator: '')
      = bootstrap_flash
      = yield

    %footer.navbar.navbar-fixed-bottom
      %p.text-center &copy; Busify 2015